name: Run BCP e2e tests
# This workflow is triggered on push and pull request to the repository
on: [push, pull_request]
jobs:
  build:
    name: BCP e2e tests in Firefox
    runs-on: ubuntu-latest
    steps:
      # This step installs dependencies
      - name: Clean install and build
        run: |
          npm init
          npm install
        env:
          CI: true
      # This step runs e2e tests in Firefox
      - name: Run BCP e2e in Firefox
        run: npm run e2e:bcprf-firefox
