name: Run BCP e2e tests
on: [push, pull_request]
jobs:
  runs-on: ubuntu-latest
  steps:
    - name: Run e2e test
      run: |
        npm ci
        npm run build
        npm run e2e:bcprf-firefox
      env:
        CI: true
